### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by molinch** [sherman89/CcmSdk.Net#1]
Thanks for the nice work @sherman89, I have not yet tried your wrapper but it helps to understand CCMSDK (at the moment we use the weird sample provided by Citrix).

On our side we are experiencing weird behaviours with it and I'm wondering if you faced such issues too.
Our flow is:
- we create multiple CCM instances (in your case that's called CommonConnectionManager)
- each of those is initialized exactly once with a unique name
However it seems like when having at the same time two instances running (but for != application names), each of them gets events for the other one (things get mixed).
Did you face this issue?

Last question, did you understand what is the concept of connectionId ?
While sessionId is pretty clear, connection id isn't so I have to say. It seems like for a given session you may get multiple connection ids, each time it looks like they are incremented.

**Comment by sherman89** [comment]
Thank you @molinch 🙂 Sorry for the late reply. 

Unfortunately I didn't have the chance to try multiple instances, and I no longer have a Citrix environment at my disposal to play with. 

Also I don't know what the concept of the connectionId is either. Citrix might be able to answer that if you create an issue in their CCM GitHub page?

Sorry that I couldn't help! Maybe if I have the time and an environment to use I can try to investigate more.

**Comment by molinch** [comment]
No worries thanks for the help :)
